[package]
name = "openarm-simulator-core-rs"
version = "0.1.0"
edition = "2024"
rust-version = "1.89"
publish = false

[dependencies]
mujoco-core-rs = { path = "../mujoco-core-rs", features = ["serde"] }
damiao-can-rs = { path = "../damiao-can-rs", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
mint = { version = "0.5.9", features = ["serde"] }
uom = { version = "0.38", default-features = false, features = ["std", "si", "f32", "f64", "serde"] }
